export const config = {
  email: {
    type: 'smtp',
    host: process.env.EMAIL_SERVICE_HOST,
    secure: true,
    port: 465,
    tls: {
      rejectUnauthorized: false,
    },
    auth: {
      user: process.env.EMAIL_SERVICE_EMAIL,
      pass: process.env.EMAIL_SERVICE_PASSWORD,
    },
  },
  oauthProviders: {
    'facebook-login': {
      provider: 'facebook',
      module: 'passport-facebook',
      profileFields: [
        'gender',
        'link',
        'locale',
        'name',
        'timezone',
        'verified',
        'email',
        'updated_time',
        'displayName',
        'id',
      ],
      clientID: process.env.FB_CLIENT_ID,
      clientSecret: process.env.FB_CLIENT_SECRET,
      callbackURL: '/auth/thirdparty/facebook/callback',
      authPath: '/auth/thirdparty/facebook',
      callbackPath: '/auth/thirdparty/facebook/callback',
      successRedirect: '/auth/account',
      failureRedirect: '/login',
      scope: ['email'],
      failureFlash: true,
      proxy: true,
    },
    'google-login': {
      provider: 'google',
      module: 'passport-google-oauth2',
      strategy: 'OAuth2Strategy',
      clientID: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      callbackURL: '/auth/thirdparty/google/callback',
      authPath: '/auth/thirdparty/google',
      callbackPath: '/auth/thirdparty/google/callback',
      successRedirect: '/auth/account',
      failureRedirect: '/login',
      scope: ['email', 'profile'],
      failureFlash: true,
      proxy: true,
    },
    'twitter-login': {
      provider: 'twitter',
      module: 'passport-twitter',
      strategy: 'OAuth2Strategy',
      consumerKey: process.env.TWITTER_CONSUMER_KEY,
      consumerSecret: process.env.TWITTER_CONSUMER_SECRET,
      callbackURL: '/auth/thirdparty/twitter/callback?source=twitter',
      authPath: '/auth/thirdparty/twitter',
      callbackPath: '/auth/thirdparty/twitter/callback',
      successRedirect: '/auth/account',
      failureRedirect: '/login',
      includeEmail: true,
      scope: ['email', 'profile'],
      failureFlash: true,
      proxy: true,
    },
    oauth2: {
      provider: 'oauth2',
      module: 'passport-oauth2',
      strategy: 'OAuth2Strategy',
      authPath: '/auth/thirdparty/oauth2',
      callbackPath: '/auth/thirdparty/oauth2/callback',
      successRedirect: '/auth/account',
      failureRedirect: '/login',
      scope: ['email', 'profile'],
      failureFlash: true,
      clientID: process.env.OAUTH_CLIENT_ID,
      clientSecret: process.env.OAUTH_SECRET,
      callbackURL: `${process.env.HOST}:${process.env.REST_PORT}/auth/thirdparty/oauth2/callback`,
      authorizationURL: 'http://localhost:9000/oauth/dialog',
      tokenURL: 'http://localhost:9000/oauth/token',
      proxy: true,
    },
  },
};
